src/index.ts, src/ipc/print.ts, src/preload.ts
This commit adds silent printing by calling `kiosk.print()` from within the hosted webpage. The global `kiosk` is added by the `preload.js` script and will expose more features in the future.
=> feat: enable silent printing

README.md, src/index.ts, src/ipc/get-battery-info.ts, src/preload.ts
This enables hosted web pages to get the battery status without having to use the deprecated Battery Status API: https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API.
=> feat: add `kiosk.getBatteryInfo`

src/index.ts, src/ipc/get-printer-info.ts, src/ipc/print.ts, src/preload.ts, src/utils/getPreferredPrinter.ts, types/electron.d.ts
This method allows callers to determine which printers are connected and which is the default. This commit also modifies `kiosk.print` to accept a device name to print to.
=> feat: add `kiosk.getPrinterInfo` API

src/ipc/get-battery-info.test.ts, src/ipc/get-battery-info.ts
We should probably just replace this with a call to `upower --dump`, but the format of this is nicer. Really, though, we should just listen for upower events on dbus so we don't have to poll.
=> fix: look for BAT0 or BAT1

jest.config.js
Otherwise jest tries to look in there and gets confused.
=> test: ignore 'out' directory

__mocks__/usb-detection.ts, src/ipc/get-device-list.test.ts, src/ipc/get-device-list.ts, src/ipc/manage-device-subscription.ts, src/utils/DeviceChangeListeners.ts, src/utils/Listeners.test.ts, src/utils/Listeners.ts, src/utils/usb.test.ts, src/utils/usb.ts, test/fakeDevice.ts
Rather than forcing consumers to separately get the device list and also listen for changes, fire change events as if all existing devices were added when the listening started.
=> feat: trigger change events for initial devices

.github/workflows/ci.yml
This should prevent `package.json` and `yarn.lock` from getting out of sync.
=> ci: install dependencies with frozen lockfile

src/utils/printing/index.ts
This was a regression caused by trying to satisfy eslint. We should add tests here, but I don't have time right now.
=> fix(printing): actually call autoconfigure code

jest.config.js
These were happening because jest didn't know to ignore `dist` and `out` directories when looking for _modules_, not _test_ files. This corrects the config so that jest ignores those directories.
=> test: prevent `jest-haste-map` errors from showing

src/index.ts, src/utils/options.test.ts, src/utils/options.ts
Disallow devtools access  by default when packaged. Devtools may still be opened with Ctrl+Shift+I in development.
=> fix: disable devtools in production

.github/workflows/ci.yml
All builds are failing with this:
```
Err:1 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libudev-dev amd64 237-3ubuntu10.33
404  Not Found [IP: 52.177.174.250 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_237-3ubuntu10.33_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
=> ci: try to fix native package installs

package.json, src/ipc/print.test.ts, src/ipc/print.ts, src/utils/exec.test.ts, src/utils/exec.ts, yarn.lock
If we never write a temp file to disk we never run the risk of that data being preserved longer than we want it to be.
=> refactor(security): print by piping to `lpr` instead of temp file

README.md, src/index.ts, src/ipc/get-usb-drives.test.ts, src/ipc/get-usb-drives.ts, src/ipc/mount-usb-drive.ts, src/ipc/unmount-usb-drive.test.ts, src/ipc/unmount-usb-drive.ts, src/preload.ts
- use `fs` module for file system operations
- use `path.join` for path manipulation
- organize imports
- fix lint warnings
=> refactor: make USB drive code more idiomatic

src/ipc/saveAs.test.ts, src/ipc/saveAs.ts, src/preload.ts, src/utils/FileWriter.test.ts, src/utils/FileWriter.ts, types/kiosk-window.d.ts
Primarily, this allows setting the default suggested file name and/or the directory to present by default in the save dialog. Some options may be macOS-only.
=> feat(saveAs): allow passing options to save dialog

src/ipc/get-usb-drives.ts
I don't know why, but the drives exposed through Parallels do not have this for me.
=> fix: allow USB drives without "part" in the name

src/ipc/clock.test.ts, src/ipc/clock.ts, src/utils/exec.ts
Now trying to set the clock while NTP is on will yield this sensible error message:
=> fix: propagate stderr from `setClock` on failure

src/ipc/get-usb-drives.ts
Reverts votingworks/kiosk-browser#63
=> Revert "fix: allow USB drives without "part" in the name"

README.md, jest.config.js, package.json, src/index.ts, src/ipc/file-system-get-entries.test.ts, src/ipc/file-system-get-entries.ts, src/ipc/file-system-make-directory.test.ts, src/ipc/file-system-make-directory.ts, src/ipc/file-system-read-file.test.ts, src/ipc/file-system-read-file.ts, src/ipc/file-system-write-file.test.ts, src/ipc/file-system-write-file.ts, src/ipc/saveAs.test.ts, src/ipc/saveAs.ts, src/preload.ts, src/utils/FileWriter.test.ts, src/utils/FileWriter.ts, src/utils/OpenFiles.ts, src/utils/access.test.ts, src/utils/access.ts, src/utils/options.test.ts, src/utils/options.ts, types/kiosk-window.d.ts, yarn.lock
These APIs build on the expanded file access permissions introduced in https://github.com/votingworks/kiosk-browser/pull/61. There are APIs for reading files, writing files, and reading the contents of a directory. These will allow building a custom file load/save interface if desired, though it wouldn't have all the features that might be desired such as creating folders or renaming files.
=> feat: add a few file system access APIs

package.json, yarn.lock
Noticed this dependency was missing when testing building/running the current main branch of kiosk-browser from vx-complete-system
=> Add missing uuid dependency

src/ipc/print.test.ts, src/ipc/print.ts, types/kiosk-window.d.ts
Adds a `sides` option to `kiosk.print` which allows specifying the duplex mode.
=> feat: allow simplex printing

src/ipc/clock.test.ts, src/ipc/clock.ts
Setting the time first and then the timezone results in the wrong time being set when the timezone differs from the current system timezone. This is because setting the time to e.g. 12:00:00 when in Pacific Time and then setting the time zone to Eastern Time will update the time to 15:00:00.
Closes votingworks/vxsuite#410
=> fix: set datetime & timezone correctly

README.md, src/ipc/get-battery-info.test.ts, src/ipc/get-battery-info.ts, src/preload.ts, types/kiosk-window.d.ts
In production all our devices have batteries, but this may not always be true. In addition, running in development on a desktop means there will be no batteries. Frontends will now check that there is a battery before trying to check its status.
Refs https://github.com/votingworks/vxsuite/pull/1289
=> fix(hardware): handle devices without batteries

src/ipc/get-printer-info.test.ts, src/ipc/get-printer-info.ts
I'm not sure that this is the right long term strategy but I believe should mitigate the printer not connected issue for now. The issue is when getting the connected device URI's it sometimes does not have the printer yet causing it to fail. This adds some retries when there is no printer connected. I only make it retry twice as the issue is so rare I think this should be sufficient but I plan to leave this running overnight to make sure it never happens. In practice 1 retry has always solved it in my (admittedly limited) testing. 
Note: This does cause the new-device-attached logs that happen here: https://github.com/votingworks/vxsuite/blob/main/libs/ui/src/hooks/use_hardware.ts#L139 to all print an extra time when the retry occurs, I'm not sure if that is potentially problematic. …
=> fix(kiosk) add retries when connecting printer

script/install-dependencies.sh
@umbernhard is adding this to the setup-machine script in vxsuite-complete-system but in order for kiosk-browser to run on debian in dev you need cups installed or lpinfo won't work.
=> Install cups on debian

src/index.ts, src/ipc/reboot.test.ts, src/ipc/reboot.ts, src/preload.ts
We will need this for https://github.com/votingworks/vxsuite/issues/1401 so adding it as a first step. 
I'm imagining having separate functions to change the boot order, see if the USB drive is available to be put in the boot order, and actually reboot, so that we can show on the frontend what step we're on and since we will sometimes reboot without changing the boot order (if the usb drive isn't available in efibootmgr yet) and sometimes after changing the boot order. 
Is there any way we should be checking permissions at the kiosk-browser level? To make sure that you have to be a superadmin to do change the boot order?
=> feat(kiosk) add reboot function to kiosk browser

README.md, src/index.ts, src/ipc/prepare-boot-usb.test.ts, src/ipc/prepare-boot-usb.ts, src/preload.ts
Adds a function to prepare the device to boot, on the next boot, from the bootable drive associated with the given usb device. I made it take the usb device name as an input but after testing on clonezilla I'm not 100% sure that makes the most sense so open to suggestions. 
Basically when the boot stick is clonezilla there are two partitions, they are different parts of the same "partition uuid" that efibootmgr cares about. For example. /dev/sda1 might map to the partition uuid "123456789-01" and /dev/sda2 would map to "123456789-02". `efibootmgr -v` will give the id `0x123456789` and just have one bootable entry so it will actually work regardless of whether you call the function with sda1 or sda2, as I am just ignoring the part of the uuid after the `-`. I'm not sure if it will be …
=> feat(kiosk) add prepare to boot from usb function

src/ipc/prepare-boot-usb.test.ts, src/ipc/prepare-boot-usb.ts
Adds a fallback boot option to return true and boot from the "Boot Menu" if that is a labelled entry in efibootmgr. Also fixes the regex as the boot number is hexadecimal and can contain letters A-F.
=> fix(kiosk) add fallback boot menu bootable option and fix regex

.vscode/settings.json
The latest version of TS that ships wiith VS Code is not fully compatible with the code written in kiosk-browser. This fixes it to use the one installed by `yarn`. We should also update TypeScript.
=> chore(ts): configure VS Code to use installed TS

src/utils/options.ts
The documentation says `-v` is equivalent to `--add-file-perm`, so this makes that real.
=> fix: handle `-v` option

package.json, src/index.ts, yarn.lock
Depends on #115
Part of the reason for #114 was that `app.remote` is no longer available by default in renderer processes. `electron-json-storage` used this, but the newer version doesn't try to if you set the data path yourself. So that's what we do now.
See https://github.com/electron-userland/electron-json-storage#running-on-electron-10-renderer-processes
=> fix: upgrade `electron-json-storage`

src/ipc/clock.ts, src/preload.ts, types/kiosk-window.d.ts
Depends on #116
In Electron v12 they made `contextIsolation: true` the default, which means we can no longer access certain things from renderer processes. Thus, we can't just assign `kiosk` to `window`. We have to use [`contextBridge.exposeInMainWorld`](https://www.electronjs.org/docs/latest/api/context-bridge#contextbridgeexposeinmainworldapikey-api). Because of how this API works we cannot expose a class with prototype methods and have them be callable, so instead we now build `Kiosk` objects using a factory pattern instead. This makes more sense anyway since they're not really a class with internal state.
Also updates the `KioskBrowser` types from `vxsuite`, which by necessity has had the more up-to-date version.
Fixes #114
=> fix: bring back `kiosk` global

src/index.ts, src/ipc/device-subscription.ts, src/ipc/get-printer-info.test.ts, src/ipc/get-printer-info.ts, src/ipc/print.test.ts, src/ipc/print.ts, src/ipc/printer-subscription.test.ts, src/ipc/printer-subscription.ts, src/ipc/sign.test.ts, src/preload.ts, src/utils/buildDevicesObservable.ts, src/utils/buildIpcMainForwardingObservable.test.ts, src/utils/buildIpcMainForwardingObservable.ts, src/utils/buildPrinterInfoObservable.ts, src/utils/printing/autoconfigurePrinter.test.ts, src/utils/printing/autoconfigurePrinter.ts, src/utils/printing/configurePrinterFromDevice.ts, src/utils/printing/getPrinterConfigForDevice.ts, src/utils/usb.test.ts, src/utils/usb.ts, test/fakeDevice.ts, test/integration/support/minitest.ts, test/integration/tests/kiosk.test.ts, test/integration/vite.config.ts, test/ipc.ts, types/kiosk-window.d.ts, types/usb-detection.d.ts
Fixes #120 
Added a bare-bones integration test for devices and tested both `devices` and `printers` subscriptions in `about:blank` and `devices` in Election Manager. Requires this patch be applied in `vxsuite`:
```diff
diff --git a/libs/ui/src/hooks/use_devices.ts b/libs/ui/src/hooks/use_devices.ts
index 34a69360..c4828536 100644
--- a/libs/ui/src/hooks/use_devices.ts
+++ b/libs/ui/src/hooks/use_devices.ts
@@ -7,7 +7,6 @@ import {
isPrecinctScanner,
} from '@votingworks/utils';
import { useEffect, useState } from 'react';
-import { map } from 'rxjs/operators';
import useInterval from 'use-interval';
import { useCancelablePromise } from './use_cancelable_promise';
import { usePrevious } from './use_previous';
@@ -64,13 +63,13 @@ export function useDevices({ hardware, logger }: Props): …
```
=> fix: make `kiosk.devices` and `kiosk.printers` work again

src/index.ts, src/ipc/reboot-to-bios.test.ts, src/ipc/reboot-to-bios.ts, src/preload.ts, types/kiosk-window.d.ts
As part of being able to update equipment in the field, the ability to reboot to BIOS is an important complement to "Reboot to USB".
=> add kiosk.rebootToBIOS()

src/index.ts, src/ipc/sync-usb-drive.test.ts, src/ipc/sync-usb-drive.ts, src/preload.ts, src/utils/promisifiedExec.ts, types/kiosk-window.d.ts
Adds a new `kiosk-browser` API which allows us to trigger (and `await`) data to be flushed to the removable disk.
=> add kiosk.syncUsbDrive

src/index.ts, src/ipc/cancel-speak.test.ts, src/ipc/cancel-speak.ts, src/ipc/speak.test.ts, src/ipc/speak.ts, src/preload.ts, test/deferred.ts, types/kiosk-window.d.ts
Adds a `speak` and `cancelSpeak` API to use Linux's speech-dispatcher via `spd-say`.
=> speak & cancelSpeak APIs

src/ipc/get-usb-drive-info.ts
Forgot to add this into the `lsblk` query.
=> get label attribute when polling USBs

src/ipc/speak.ts, types/kiosk-window.d.ts
assumes an `spd-cache` executable in the path that does the same thing as `spd-say` except it just caches the wav file for the next time that string is called with `spd-say`. 
This is useful for tts that is not sufficiently real-time, since all the text we speak is determined at election loading time.
=> feat(speak): add ability to just cache an utterance, vs. speaking it.

src/index.ts, src/ipc/show-save-dialog.test.ts, src/ipc/show-save-dialog.ts, src/preload.ts, types/kiosk-window.d.ts
We have kiosk functions to "Save As" which are intertwined with writing the file through the kiosk. This is a simpler endpoint that simply allows us to leverage the system file dialog and yield a path for saving.
=> Add "Show Save Dialog" Channel

script/install-dependencies.sh
The `python` package seems to be removed from Debian 12. I believe this will work with both 11 and 12.
=> build(deps): install `python3` package

src/ipc/print.test.ts, src/ipc/print.ts, types/kiosk-window.d.ts
To be used when printing to the iDPRT thermal label printer. I intend to add `-o media=Custom.4x6in`. I could have added `media` specifically, but I felt like it might be worth just having this escape hatch.
=> feat(print): allow passing raw `lpr` options

script/build.sh
`pnpm` does not try to fetch packages for an unknown command. This should have been included in https://github.com/votingworks/kiosk-browser/pull/155.
=> build: remove `--offline` flags

script/install-dependencies.sh
We no longer directly invoke `sudo`, nor switch on OS version.
=> chore: remove cruft from install script

Makefile
Without this, sometimes running `make build` will just do nothing. We're not using `make` to do smart incremental builds, so just run the command please `make`.
=> build: ensure `make` scripts always run

src/index.ts
Middle-clicking on a link will open it in a new window. We catch that event and block it.
Before
https://github.com/votingworks/kiosk-browser/assets/530106/029adf34-6198-4a78-8886-809e9f210fc2
After
https://github.com/votingworks/kiosk-browser/assets/530106/046c1ea7-dcdf-4f43-8ea0-aa06722aaaa7
=> Disallow opening a new window

package.json
While building images, I hit the following error, specifically at the step that builds `kiosk-browser`:
```
⨯ Please specify author 'email' in the application package.json
See https://docs.npmjs.com/files/package.json#people-fields-author-contributors
It is required to set Linux .deb package maintainer. Or you can set maintainer in the custom linux options.
(see https://www.electron.build/configuration/linux).
failedTask=build stackTrace=Error: Please specify author 'email' in the application package.json
```
Adding back an `author` object with an email seemed to do the trick. Per the error message, seems that an author is required when the `package.json` has a `build.linux` entry (the case for `kiosk-browser`, not the case for `vxsuite`).
We only recently removed this while cleaning up …
=> Add back author

src/index.ts
This PR fixes the issue where pressing Ctrl+M would minimize the kiosk-browser window, causing the screen to go black and requiring a reboot to recover.
- Added `globalShortcut` import to `src/index.ts`
- Registered a global shortcut for `Ctrl+M` that does nothing, preventing the default minimize behavior
- Added proper cleanup of global shortcuts when the app quits
The fix can be tested by:
1. Building and running the kiosk-browser
2. Pressing `Ctrl+M` - the window should remain visible instead of minimizing
3. Normal operation should be unaffected
Closes [#6601](https://github.com/votingworks/vxsuite/issues/6601)
=> fix: prevent Ctrl+M from minimizing kiosk-browser window

.github/pull_request_template.md, script/build.sh, script/install-dependencies.sh
Since kiosk-browser rarely changes, it's more efficient to build it once as a Debian package and install as needed. This PR checks for an existing package based on the version found in `package.json`. If it's found, the normal build steps are bypassed. If it's not found, the normal build steps proceed as usual. Regardless, a final package will be available in the `dist` directory for use by other build processes.
=> Use a prebuilt version of kiosk-browser when available

.circleci/config.yml, package.json
I was thinking of making an entirely separate change in `kiosk-browser` when I saw https://github.com/votingworks/vxsuite/issues/7143 and got distracted. This adds a workflow to CI which checks that a branch has a different version string than `main`. We would have to make it "required" in CI. It applies to every change, not limiting itself to files in certain directories. It does not run on `main` itself, since that would always fail. You can see an example of it failing and passing in the history of this branch.
=> add version bump check
