- package.json
- src/index.ts
- src/ipc/get-device-list.ts
- src/ipc/manage-device-subscription.ts
- src/preload.ts
- types/usb-detection.d.ts
- yarn.lock
Adds `kiosk.getDeviceList` and `kiosk.onDeviceUpdate` to get the current device list and watch for updates.
> feat: add USB device list/watch

- jest.config.js
- package.json
- src/ipc/get-battery-info.test.ts
- src/ipc/get-battery-info.ts
- src/ipc/get-device-list.test.ts
- src/ipc/get-printer-info.test.ts
- src/ipc/get-printer-info.ts
- src/ipc/print.test.ts
- src/ipc/print.ts
- src/preload.ts
- src/utils/Listeners.test.ts
- src/utils/Listeners.ts
- src/utils/exec.test.ts
- src/utils/exec.ts
- src/utils/getPreferredPrinter.test.ts
- src/utils/getPreferredPrinter.ts
- src/utils/getURL.test.ts
- src/utils/readFile.test.ts
- src/utils/readFile.ts
- src/utils/screen.test.ts
- src/utils/screen.ts
- test/fakeIpc.ts
- test/fakePrinter.ts
- test/mockOf.ts
- yarn.lock
Also adds a bunch of tests and refactors stuff. Sorry this isn't better split into commits.
> feat: allow multiple listeners for device change

- src/preload.ts
We were passing `undefined` as the argument for `deviceName`, which over IPC gets coerced to `null` since we're passing through JSON. This ensures the default parameter in the `print` IPC handler is used which uses the first connected printer it can find.
> fix: ensure printing to the default printer works

- test/print-config/print-config.json
Updates the test printer config to be more realistic. This is the actual product ID for that HP printer.
> test: update printer config

- src/ipc/print.test.ts
- src/ipc/print.ts
let's print background images by default. We can later make this an option if we don't want it.
Resolves #22
> print background images

- package.json
- src/ipc/print.test.ts
- src/ipc/print.ts
- src/preload.ts
- src/utils/printing/options.test.ts
- src/utils/printing/options.ts
- yarn.lock
These aren't hooked up anywhere, but can be proxied to a page.
> feat: add some utilities for getting print options

- src/ipc/print.test.ts
- src/ipc/print.ts
> fix bad list membership call and add test to check

- .github/workflows/ci.yml
- jest.config.js
We should bring it up to 100 over time.
> test(coverage): don't let coverage go down

- src/index.ts
- src/ipc/quit.test.ts
- src/ipc/quit.ts
- src/preload.ts
- types/kiosk-window.d.ts
This allows hosted web content to request that the browser quit.
> feat: add `kiosk.quit()` API

- __mocks__/usb-detection.ts
- src/utils/usb.ts
Each commit has a description.
> Minor USB fixes

- README.md
> docs: add development instructions

- src/ipc/get-battery-info.test.ts
- src/ipc/get-printer-info.test.ts
- src/ipc/print.test.ts
- test/ipc.ts
This moves the ugliness mostly into one place rather than forcing each test to do it.
> test: improve IPC testing

- src/ipc/get-usb-drives.test.ts
- src/ipc/get-usb-drives.ts
> fix: readlink relative --> absolute path

- __mocks__/electron-json-storage.ts
- package.json
- src/index.ts
- src/ipc/storage-clear.test.ts
- src/ipc/storage-clear.ts
- src/ipc/storage-get.test.ts
- src/ipc/storage-get.ts
- src/ipc/storage-remove.test.ts
- src/ipc/storage-remove.ts
- src/ipc/storage-set.test.ts
- src/ipc/storage-set.ts
- src/preload.ts
- yarn.lock
an API that looks a lot like `localStorage` only not limited in size.
> storage API

- src/ipc/print.test.ts
- src/ipc/print.ts
addresses https://github.com/votingworks/vxmail/issues/127
> duplex printing at all times

- README.md
- package.json
- src/ipc/print.test.ts
- src/ipc/print.ts
- src/preload.ts
- types/kiosk-window.d.ts
- yarn.lock
> feat: allow specifiying the number of print copies

- README.md
- src/index.ts
- src/ipc/saveAs.test.ts
- src/ipc/saveAs.ts
- src/utils/FileWriter.test.ts
- src/utils/FileWriter.ts
- src/utils/access.test.ts
- src/utils/access.ts
- src/utils/options.test.ts
- src/utils/options.ts
This is a BREAKING CHANGE because the CLI API for configuring file access has changed.
> feat: improve file access permissions

- jest.config.js
Merged in some changes that were not subject to the higher threshold numbers.
> test(coverage): lower "branches" threshold

- src/ipc/mount-usb-drive.test.ts
- src/ipc/mount-usb-drive.ts
- src/preload.ts
> feat(usb): allow specifying the mount label

- src/ipc/get-usb-drives.test.ts
- src/ipc/get-usb-drives.ts
I'm not entirely sure this is the best way to solve the phantom usb drive problem but essentially this, as part of checking for the current usb devices will also check for and clean up any "phantom" usb drives. This feels a bit strange to have be a side effect of getUsbDrives() but... I'm not sure where else it should live. 
Essentially it uses findmnt to find currently mounted directories and then filters for which of those were usb drives created by kiosk browser (mountUsbDrive mounts everything as usb-drive-{deviceId}) that are NOT currently detected devices. Then it unmounts those directories which cleans them up from the filesystem. 
https://zube.io/votingworks/vxsuite/c/3043
> feat(kiosk-browser): clean up phantom unmounted usb drive directories

- src/ipc/get-usb-drives.test.ts
- src/ipc/get-usb-drives.ts
When a drive is removed but not unmounted it will still have a mount entry, but its source will be missing. This changes the auto-cleanup code in `getUsbDrives` to look at all mounted file systems to determine which if any are missing their source. Those which are will be unmounted.
This means that we're no longer restricted to cleaning up mounts matching `/**/usb-drive*`.
Mostly taken from https://github.com/votingworks/kiosk-browser/pull/76#discussion_r604319695.
> fix: unmount anything missing its source

- script/install-dependencies.sh
Without this debian does not have 'lpr' so anything involving printing will explode.
> fix(kiosk) install cups-bsd on debian to install the lpr command

- package.json
- yarn.lock
This fixes votingworks/vxsuite#1377. See more info at https://github.com/MadLittleMods/node-usb-detection/pull/138
> Switch usb-detection over to a patched branch

- .github/workflows/ci.yml
- src/ipc/sign.test.ts
- src/ipc/sign.ts
- src/utils/options.ts
- test/integration/run
This lets us using TPMs or other signing oracles to sign data.
> Adds support for arbitrary signing script

- src/ipc/prepare-boot-usb.test.ts
- src/ipc/prepare-boot-usb.ts
a good chunk of https://github.com/votingworks/vxsuite/issues/1862
> fix(usb-booting): go for any Linpus lite or USB HDD boot entry

- src/index.ts
- src/preload.ts
- types/kiosk-window.d.ts
tests pass locally, same kiosk-browser issue.
> fix(naming): BIOS --> Bios.

- src/index.ts
- src/ipc/power-down.test.ts
- src/ipc/power-down.ts
- src/preload.ts
- types/kiosk-window.d.ts
Adds the ability to power down the machine through the software. 
https://github.com/votingworks/vxsuite/issues/3178
> Add power down function

- src/index.ts
- src/ipc/capture-screenshot.test.ts
- src/ipc/capture-screenshot.ts
- src/ipc/show-open-dialog.test.ts
- src/ipc/show-open-dialog.ts
- src/preload.ts
- types/kiosk-window.d.ts
Used by the dev dock (see https://github.com/votingworks/vxsuite/pull/3314)
> Add screenshot and dialog IPC methods

- README.md
Issue link: https://github.com/votingworks/vxsuite/issues/5028
More README updates - this one was largely up-to-date already
> Update README in prep for cert
